[env:m5cardputer-adv]
platform = espressif32@6.7.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_protocol = esp-builtin
upload_port = COM5
monitor_port = COM5
build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
lib_deps =
    m5stack/M5Cardputer
    mikalhart/TinyGPSPlus
    jgromes/RadioLib @ ^7.2.1
    SD
    bitbank2/JPEGDEC
